[package]
name = "solana-web3-rust"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
borsh = "0.9"
solana-client = "1.10.29"
solana-sdk = "1.10.29"
eyre = "0.6.8"
